-- MySQL Script generated by MySQL Workbench
-- Fri Mar 22 11:54:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sollarium
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sollarium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sollarium` DEFAULT CHARACTER SET utf8 ;
USE `db_sollarium` ;

-- -----------------------------------------------------
-- Table `db_sollarium`.`tb_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sollarium`.`tb_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sollarium`.`tb_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sollarium`.`tb_products` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `inventory` INT NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `description` VARCHAR(255) NULL,
  `tb_category_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_products_tb_category_idx` (`tb_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_products_tb_category`
    FOREIGN KEY (`tb_category_id`)
    REFERENCES `db_sollarium`.`tb_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sollarium`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sollarium`.`tb_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `photo` VARCHAR(255) NULL,
  `tb_products_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_user_tb_products1_idx` (`tb_products_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_user_tb_products1`
    FOREIGN KEY (`tb_products_id`)
    REFERENCES `db_sollarium`.`tb_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
